version: "3.8"
services:
  dev-postgres:
    image: postgres:16.3-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-template
    restart: always
    networks:
      - lesson
networks:
  lesson: